FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

RUN apk add --no-cache \
    ffmpeg \
    make \
    g++ \
    python3 \
    && npm install

COPY . .

ENV PORT=3000
ENV VIDEOS_DIR=/videos

RUN mkdir -p /videos

EXPOSE 3000

CMD ["node", "app.js"]
